import {} from './Models/template.js'
import { getListOfIngredients } from './data/ListIngredients.js'
import { getListOfAppliance } from './data/ListAppareils.js'
import { getListOfUstensils } from './data/ListUstensils.js'
import {} from './Models/listsDropdown.js'